### PR TITLE
Allow using custom configuration file in fink_kafka

### PR DESCRIPTION
**Pull request by cAbhi15**
**IMPORTANT: Please create an issue first before opening a Pull Request.**
Linked to issue(s): #279 

## What changes were proposed in this pull request?
- allow the use of custom configuration file in `fink_kafka`

## How was this patch tested?
- manually

### CODE REVIEW

**Comment by JulienPeloton** [comment]
Thanks @cAbhi15 - the job is failing because of a new version of pyarrow (see #284). Could you pull new change from master into this branch to fix the failure?

**Comment by JulienPeloton** [comment]
Thanks @cAbhi15 - so if I understand correctly, the new syntax to start a Kafka cluster with a custom configuration file is `fink_kafka start -c <some_file>`?

**Comment by cAbhi15** [comment]
Yes @JulienPeloton

`fink_kafka start -c <some_file>` or
`fink_kafka -c <some_file> start` would work.

**Comment by JulienPeloton** [comment]
Great thanks!

**Pull request merged**
