### PR TITLE
Docker Toolbox is making use of a specific IP address (that is not localhost)

### PR DESCRIPTION
**Pull request by marcol480**
Linked to issue(s): https://github.com/astrolabsoftware/fink-broker/issues/199

### CODE REVIEW

**Comment by JulienPeloton** [comment]
Thanks @marcol480 for the change! Actually, there are two different things in your PR, one is related to #199 and the other is #198. 

I will isolate the change for #198 in another PR, while keeping the relevant change in this PR. I guess the action item from your side you be to revert change in `bin/checkstream.py`.

**Comment by JulienPeloton** [comment]
Also the checks are failing because of changes in the configuration. The change from `localhost` to `192.168.99.100` is only required for users having Toolbox (which is not the case for the continuous integration for instance). So we should think about a mechanism that switches this depending on the way docker is accessed.

**Comment by marcol480** [comment]
> Thanks @marcol480 for the change! Actually, there are two different things in your PR, one is related to #199 and the other is #198.
> 
> I will isolate the change for #198 in another PR, while keeping the relevant change in this PR. I guess the action item from your side you be to revert change in `bin/checkstream.py`.

Thanks Julien, sure it may have been better to have separate pull requests but I was not sure and I did one. In the end I agree the Toolbox issue is a minor issue -- I just wanted to mention it, in order to keep this in mind.

**Comment by JulienPeloton** [comment]
I'm closing this PR for time being as the modifications bring here are mostly not related to docker toolbox and they have been solved in #245. 

Also any problem related to toolbox is likely to disappear with the rise of Dropbox desktop.

**Pull request closed without merging**
