### PR TITLE
SNAD processor and anomaly detection

### PR DESCRIPTION
**Pull request by VoidDruid**
Linked to issue(s): Closes [553](https://github.com/astrolabsoftware/fink-broker/issues/553) and a part of [anomaly detection](https://github.com/astrolabsoftware/fink-science/issues/264)

## What changes were proposed in this pull request?

Use SNAD processor from [PR 139](https://github.com/astrolabsoftware/fink-science/pull/139) in post-processing of the fink alerts. Use anomaly_score processor to add anomaly score [PR 265](https://github.com/astrolabsoftware/fink-science/pull/265).

## How was this patch tested?

With `fink-test --no-integration`, and the module itself was tested in the fink-science repo.

**NOT READY**: this PR requires [PR 265](https://github.com/astrolabsoftware/fink-science/pull/265) to be merged first.

### CODE REVIEW

**Comment by JulienPeloton** [comment]
Hi @VoidDruid -- thanks for the addition -- could you update your branch by pulling the latest change from the master branch?

**Comment by JulienPeloton** [comment]
Hi @VoidDruid -- there has been some change in the name of the module (see https://github.com/astrolabsoftware/fink-science/pull/171). Could you update this PR with the new name?

**Comment by VoidDruid** [comment]
> Hi @VoidDruid -- there has been some change in the name of the module (see [astrolabsoftware/fink-science#171](https://github.com/astrolabsoftware/fink-science/pull/171)). Could you update this PR with the new name?

done

**Comment by VoidDruid** [comment]
Updated with anomaly detection module. Not a separate PR because it uses `lc_features`.

**Review by JulienPeloton — APPROVED** [review]

**Pull request merged**
