### PR TITLE
adding last limit per filter

### PR DESCRIPTION
**Pull request by anaismoller**
**IMPORTANT: Please create an issue first before opening a Pull Request.**
Linked to issue(s): Closes [915](https://github.com/astrolabsoftware/fink-broker/issues/915)

## What changes were proposed in this pull request?
Added last limit to data for RF SNIa early classification

## How was this patch tested?
In the cluster, locally (probably need some refactor)

### CODE REVIEW

**Comment by anaismoller** [comment]
Some tests did not pass, shall we worry? @JulienPeloton

**Comment by JulienPeloton** [comment]
all tests are good :-)

**Comment by anaismoller** [comment]
shall I merge then?

**Review by JulienPeloton — APPROVED** [review]

**Comment by JulienPeloton** [comment]
Merged!

**Pull request merged**
