### PR TITLE
[WIP] Issue/126/GitHub templates

### PR DESCRIPTION
**Pull request by tallamjr**
It was quite funny to see this as an issue as it is something I was trying to learn about and do for one of my personal project anyway! :-) I have had a go at adding the right files in addition to the potential layout one might prefer.

This adds `.github` folder as well as `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md` files which allow for automatic templates to be rendered when a user opens an issue or new pull request.

This is currently a work in progress and feedback on phrasing is preferred.

_Note. This PR was originally opened in #128 but it was discovered the wrong issue was being referenced_

### CODE REVIEW

**Comment by JulienPeloton** [comment]
Thanks @tallamjr! 

The issue template is great as it is.

I would suggest some modifications for the PR one:

```
**IMPORTANT: Please create an issue first before opening a Pull Request.**
Linked to issue(s): _put link_

## What changes were proposed in this pull request?

<!-- You can skip this if you're fixing a typo or adding an app to the Showcase. -->

How is the issue this PR is referenced against solved with this PR?

## How was this patch tested?

```

What do you think?

**Comment by tallamjr** [comment]
> How was this patch tested?

Ah yes, of course, very important!

I agree with the modifications, makes it nice and clearer 👍 

I have made the changes and re-pushed. I'm happy to make further alterations if
you would like.

**Comment by JulienPeloton** [comment]
Thanks for the modifications! LGTM :-)

**Comment by JulienPeloton** [comment]
Merged! Thanks @tallamjr

**Pull request merged**
